### ISSUE TITLE
動作しません　Device

### ISSUE THREAD

**Issue by usasho** [pstuvwx/Voice_DiscoGAN#10]
/home/scss/DeepLearning/音声合成/voiceconv/dataset.py:22: WavFileWarning: Chunk (non-data) not understood, skipping it.
  bps, data = wav.read(path)
Traceback (most recent call last):
  File "trainer.py", line 189, in <module>
    main()
  File "trainer.py", line 167, in main
    updater = Updater(train_iter_a, train_iter_b, opt_g_a, opt_g_b, opt_d_a, opt_d_b, device=args.gpu)
  File "/home/scss/DeepLearning/音声合成/voiceconv/updater.py", line 34, in __init__
    self.device = device
AttributeError: can't set attribute

音声データ　A45分、B35分　16Bit　16000Hz
使用環境
CPU　Core i３
GPU　GT710 OC
CUDA 10.2
RAM 16GB
LinuxMint

**Comment by mjyn** [comment]
try use chainer version 6.x

**Comment by usasho** [comment]
ありがとうございます　動作確認しました
Chainerのバージョンが高すぎたようです　

Thank you
Chainer version seems too high

**Comment by game4d** [comment]
修改为：self._device = device
试试
